from enum import Enum


class RunStagesEnum(Enum):
    INITIALIZING_SOURCE_STAGE = 1
    AUTHENTICATION_SOURCE_STAGE = 2
    RETRIEVING_DATA_STAGE = 3
    FINISHING_SOURCE_STAGE = 4
    INITIALIZING_DESTINATION_STAGE = 5
    AUTHENTICATION_DESTINATION_STAGE = 6
    LOAD_DATA_STAGE = 7
    DONE = 8

class TasksEnum(Enum):
    SOURCE = "SOURCE"
    DESTINATION = "DESTINATION"

class UpdateRunHistoryActionEnum(Enum):
    SOURCE_PIPELINE_END = "SOURCE_PIPELINE_END"
    DESTINATION_PIPELINE_START = "DESTINATION_PIPELINE_START"
    DESTINATION_PIPELINE_END = "DESTINATION_PIPELINE_END"
    ROWS_RETRIEVED = "ROWS_RETRIEVED"
    ROWS_INSERTED = "ROWS_INSERTED"

class EnvironmentVariablesEnum(Enum):
    TASK = "TASK"
    PIPELINE_ID = "PIPELINE_ID"
    PIPELINE_RUN_HISTORY_ID = "PIPELINE_RUN_HISTORY_ID"
    SERVER_ENDPOINT = "SERVER_ENDPOINT"
    SERVER_API_KEY = "SERVER_API_KEY"
    APP_ENV = "APP_ENV"
    MASTER_HASH = "MASTER_HASH"

class ServerEndpointsEnum(Enum):
    pass